"""Test

Revision ID: 219d406aad4
Revises: 33818e8c4ca
Create Date: 2017-02-19 17:09:49.583291

"""

# revision identifiers, used by Alembic.
revision = '219d406aad4'
down_revision = '33818e8c4ca'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
