"""Initial creation

Revision ID: 33818e8c4ca
Revises: 
Create Date: 2017-02-19 17:08:19.284998

"""

# revision identifiers, used by Alembic.
revision = '33818e8c4ca'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
