"""Really actually work this time?

Revision ID: 47baeab852
Revises: 10e6b2ec599
Create Date: 2017-02-19 15:54:27.642581

"""

# revision identifiers, used by Alembic.
revision = '47baeab852'
down_revision = '10e6b2ec599'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('globalName', sa.String(length=250), nullable=False))
    op.add_column('member', sa.Column('nickname', sa.String(length=250), nullable=True))
    op.add_column('member', sa.Column('role', sa.String(length=250), nullable=True))
    op.drop_column('member', 'local_nick')
    op.drop_column('member', 'global_nick')
    op.drop_column('member', 'rank_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('rank_id', sa.INTEGER(), nullable=True))
    op.add_column('member', sa.Column('global_nick', sa.VARCHAR(length=255), nullable=True))
    op.add_column('member', sa.Column('local_nick', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('member', 'role')
    op.drop_column('member', 'nickname')
    op.drop_column('member', 'globalName')
    ### end Alembic commands ###
